### ISSUE TITLE
When the player places a jack down, the player can no longer play

### ISSUE THREAD

**Issue by kylesureline** [vcjhwebdev/slapjack#1]
Take a look at the following function:
```
function playerPlay() {
  var nextCard = playerHand.pop();
  cardsInPlay.push(nextCard);
  if(nextCard !== undefined) {
      cardInPlay.src = "img/cards/2x/" + nextCard + ".png";
  }
  // remove event listener after player has played
  deck.removeEventListener('click', playerPlay);
  // computer's turn
  if (!nextCard.includes("_jack")) {
    computerPlay();
  } else {
    jackPlaced();
  }
}
```

If the computer places a jack down, `computerPlay()` doesn't run, and therefore the event listener isn't placed back on the `.deck`.

Here is my suggestion. Generate a modal window to tell the user who won the "slap" (and how many cards they now have), then add the event listener back when they dismiss the modal.

Todo: Figure out how to end the game 😂

**Comment by tyzhou05** [comment]
ok will work on it next week
